import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'
import Vuesax from 'vuesax'
import 'vuesax/dist/vuesax.css'
import VueLazyload from 'vue-lazyload'
import 'vue-croppa/dist/vue-croppa.css'
import Croppa from 'vue-croppa'
import VueMatomo from 'vue-matomo';
import replaceAllInserter from 'string.prototype.replaceall';
import VueMeta from 'vue-meta'
import linkify from 'vue-linkify'

Vue.use(VueMeta)
replaceAllInserter.shim();

// Handle the First visit of user and give it a unique ID Until the user registers and
// receives a valid username
function generateGuestId() {
    // check if it's the very first time user and not only
    // a unregistered user visiting again.
    if (localStorage.getItem("guestID") === null) {
        const id = 'guest-xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
        localStorage.setItem('guestID', id)
        return id
    } else {
        // We save the guestID so we can recognise guests that are
        // coming back and giving a second thought about registering.
        return localStorage.getItem('guestID')
    }
}

const userId = () => {
    if (localStorage.getItem("token") === null) {
        return generateGuestId()
    } else {
        try {
            // Decode the JWT token to get username if exist
            return JSON.parse(atob(localStorage.getItem('token').split('.')[1]))['username']
        } catch {
            // In cases that user has not a valid token or any other
            // problems during decoding JWT Token we generate a guestID.
            return generateGuestId()
        }
    }

}
// Config for Motamo analytics
Vue.use(VueMatomo, {
    host: "https://analytics.filmclub.top/",
    siteId: 1,
    trackerFileName: 'matomo',
    router: router,
    enableLinkTracking: true,
    requireConsent: false,
    trackInitialView: true,
    disableCookies: false,
    enableHeartBeatTimer: this,
    heartBeatTimerInterval: 30,
    debug: false,
    userId: userId(),
    cookieDomain: '*.filmclub.top',
    domains: '*.filmclub.top',
    preInitActions: []
});
// Third party library for recognising links
Vue.directive('linkified', linkify)

// Vue lazy load images.
const loadimage = require('./assets/loading.gif')
const errorimage = require('./assets/err.gif')

// Truncate the text and make smaller texts like summary for a long post in home page.
Vue.filter('truncate', function (text, length, suffix) {
    if (text.length > length) {
        return text.substring(0, length) + suffix;
    } else {
        return text;
    }
});

// Replace texts generated by EditorJS to have a better looking text and post.
Vue.filter('sanitize', function (text) {
    return text.replaceAll('nbsp', ' ').replaceAll('& ;', '').replaceAll('<br>', '\n').replaceAll('script', '').replaceAll('alert', '').replaceAll('&amp;', '&')
});

// Calculate the time passed from a post or comment and return it in a user readable format.
Vue.filter('dateToString', function (text) {
    const now = new Date()
    let postDate = new Date(text)
    let Difference_In_Time = Math.floor((now.getTime() - postDate.getTime()));
    if (Math.floor(Difference_In_Time / 1000 / 60 / 60 / 24) > 0) {
        Difference_In_Time = Math.floor(Difference_In_Time / 1000 / 60 / 60 / 24)
        if (Difference_In_Time > 1) {
            Difference_In_Time += ' days ago'
        } else {
            Difference_In_Time += ' day ago'
        }
    } else if (Math.floor(Difference_In_Time / 1000 / 60 / 60) > 0) {
        Difference_In_Time = Math.floor(Difference_In_Time / 1000 / 60 / 60)
        if (Difference_In_Time > 1) {
            Difference_In_Time += ' hours ago'
        } else {
            Difference_In_Time += ' hour ago'
        }
    } else {
        Difference_In_Time = Math.floor(Difference_In_Time / 1000 / 60)
        if (Difference_In_Time > 0) {
            if (Difference_In_Time > 1) {
                Difference_In_Time += ' minutes ago'
            } else {
                Difference_In_Time += 'minute ago'
            }
        } else {
            Difference_In_Time = ' Just now'
        }
    }
    return Difference_In_Time
});

Vue.use(VueLazyload, {
    preLoad: 2,
    error: errorimage,
    loading: loadimage,
    attempt: 2
})
Vue.use(VueLazyload)

// Third party library for cropping images.
Vue.use(Croppa)
Vue.config.productionTip = false
Vue.use(Vuesax, {
    colors: {
        primary: '#1e2023',
        success: 'rgb(23, 201, 100)',
        danger: 'rgba(255,45,45,0.55)',
        warning: 'rgb(255, 130, 0)',
        dark: 'rgb(30,32,35)',
    }
})
// Initialize Vue app!
new Vue({
    router,
    store,
    render: h => h(App)
}).$mount('#app')
